name: gc

on:
  schedule:
    - cron:  '30 10 * * *'
  workflow_dispatch: # on button click
  
jobs:
  start:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: test
      run: |
        echo $(git rev-list --objects --all | grep efa24a5be7232f696d7ed3a8eaea8336c747a51e | awk '{print$2}')
        export filename=$(git rev-list --objects --all | grep efa24a5be7232f696d7ed3a8eaea8336c747a51e | awk '{print$2}' | grep '^wallpaper.*jpg$')
        echo $filename
        echo $(git log --pretty=oneline --branches -- ${filename} | wc -l)
    
    - name: run gc
      run: bash rm_overdate_file.sh
      
    - name: Git auto commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Remove overdate images
        push_options: '--force'
