name: Sync to Lsky Pro

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Remote SSH Pusblish
        uses: nerd4ever/ssh-action@0.1.0
        with:
          command: |
            bash /root/lsky-pro/update_bing.sh
          host: ${{ secrets.HOST }}
          user: root
          key: ${{ secrets.PRIVATE_KEY }}
